# Generated by Django 6.0.5 on 2026-05-26 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование товара', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='Подробное описание товара', null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите изображение товара', null=True, upload_to='products/photos/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену товара (например, 999.99)', max_digits=10, verbose_name='Цена за покупку')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания товара', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления информации о товаре', verbose_name='Дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, help_text='Выберите категорию товара', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
