# Generated by Django 6.0.5 on 2026-05-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время создания товара', null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время последнего обновления информации о товаре', null=True, verbose_name='Дата последнего изменения'),
        ),
    ]
